### ISSUE TITLE
Characteristic 'f000aa43-0451-4000-b000-000000000000' not found

### ISSUE THREAD

**Issue by Softwaremaker** [clovett/SensorTag-for-Windows#2]
Hello! First of all - Great work !
i am using a CC2650 and have paired that successfully on WP8.1. However, when i opened the app, it throws an exception - Characteristic 'f000aa43-0451-4000-b000-000000000000' not found. It just wont move after that.

I checked that it is the barometer UUID and remove all traces of it in the code but the exception just wont go away.

What am I missing ? Thanks !

**Comment by clovett** [comment]
This is fixed.  CC2650 combines Accelerometer, Magnetometer and Gyroscope into one BLE service called "Movement".  So some of the service GUIDs have changed.  Also the CC2650 adds a light sensor which is nice.  The calibration is also much simpler since it is all done in firmware now.
