### ISSUE TITLE
Does this work with the TI CC2650 SenorTag ?

### ISSUE THREAD

**Issue by Softwaremaker** [clovett/SensorTag-for-Windows#3]
I have successfully paired it with Bluetooth. but when the app opens, it says:

Characteristic 'f000aa43-0451-4000-b000-000000000000' not found

**Comment by clovett** [comment]
I have some work to do to update the software, there are some changes to the GATT profile on the new device.  I'm working on it... Feel free to help out...  I've checked in new version of the code to prepare for this work that adds version number property to each GATT service.  This way we can support both SensorTag devices with the same code base.
